# 집단 약동학 분석 {#poppk}

집단 약동학 분석은 개인별 약동학 파라미터가 다르며, 어떤 분포를 보이고, 개인별 차이는 무작위적으로 보이지만, 그렇지 않은 면도 있다는 것을 정량적으로 분석하는 것이다. 개인별로 약동학 파라미터에는 차이가 있으며, 일부는 신장, 체중, 크레아티닌 청소율 등과 같은 고정효과(fixed-effects)로 설명되고, 일부는 무작위적 변이(random variability)이다. 따라서 집단 약동학에서의 관심사는 집단 전체의 약동학 파라미터의 평균값(또는 중앙값 같은 대표값) 이 외에도 산포도(분산, 표준편차)의 정도와 개인별 약동학 파라미터 추정까지도 포함된다. 이것을 추정하는 방법으로 2-단계 접근법 (Two-Stage Approach)과 비선형 혼합-효과 모형 접근법(Nonlinear Mixed-Effects Modeling Approach)이 있다.

## 2-단계 접근법(Two-Stage Approach)

2-단계 접근법(Two-Stage Approach)은 약동학 분석에서 전형적으로 사용되는 방법이다. 이 접근법의 첫 번째 단계에서는, 개인별 농도-시간 자료로부터 비선형 회귀를 통해 개인별 약동학 파라미터를 추정하게 된다. 이는 통상 개인별로 시간별 측정값이 10 여개 이상으로 충분히 존재하는 조밀한 자료(dense data)를 이용하게 된다.

첫 번째 단계에서 얻은 개인별 파라미터는 두 번째 단계인 표본의 기술 통계량 계산을 위해 입력 자료(input data)로 활용된다(개인별 파라미터의 평균, 분산, 공분산). 즉, 1 차로 추정된 개인별 파라미터들로부터 다시 인구 전체에서의 평균(또는 중앙값 같은 대표값)이나 산포도(분산, 표준편차) 값들을 추정하는 방법이다. 전형적 통계 접근법(선형단계 회귀 분석(linear stepwise regression), 공분산 분석(covariance analysis), 군집 분석(cluster analysis))을 이용한 파라미터와 공변량(covariates) 사이의 관계(dependencies) 분석이 두 번째 단계에 포함될 수 있다. 적용 가능한 경우, 2-단계 접근법을 통해 집단의 특성을 나타내는 적절한 추정치를 얻을 수 있다.

일반적으로 파라미터의 평균 추정치는 편향되지 않지만(unbiased) 모든 실제 상황에서 무작위효과(random effects, 분산과 공분산)가 과하게 평가되는(overestimate) 경향이 있다. 이에 자료의 질(quality)과 양(quantity)에 따라 개별 자료에 다른 가중치(differential weighting)를 부여하고, 무작위효과의 공분산의 편향(bias)을 교정하는 방식으로 개선된 2-단계 접근법(global two-stage approach)이 제안되고 있다.

2-단계 접근법은 신약 개발과 평가 과정에 널리 사용되어 왔으므로 이 가이드라인에서는 상세히 다루지 않을 것이다.

## 비선형 혼합-효과 모형 접근법(Nonlinear Mixed-Effects Modeling Approach)

비선형 혼합-효과 모형(Nonlinear Mixed-Effects modeling)과 같이 적절한 수학적/통계적 분석을 적용하여 환자 대상의 집단 약동학 연구를 적절하게 수행하는 경우, 광범위한(extensive) 환자 집단에서 수행하여야 하는 임상시험의 대안으로 선호될 수 있다. 개인별 파라미터를 추정하는 전형적인 2-단계 접근법이 적용될 수 없는 희박한 자료(sparse data)에 있어서는 비선형 혼합-효과 모형과 같은 1-단계 접근법(single-stage approach)을 사용해야 한다.

약동학 및 약력학 연구가 환자에서 진행되는 경우는 전형적인 방법보다(예, 건강한 지원자) 덜 엄격하고 덜 제한적인 조건에서 자료가 수집될 수 밖에 없는 점을 고려하여 비선형 혼합-효과 모형 방법이 개발되었다고도 할 수 있다.

비선형 혼합-효과 모형 접근법은 파라미터의 분포 분석이나 집단내에서의 공변량과의 관계와 같이 개인 보다는 전체 집단을 대상으로 한다. 조밀한(dense) 시료채취를 하는 전형적인 약동학 연구 자료와 달리, 비선형 혼합-효과 모형 분석에서는 빈번하지 못한 시료채취, 또는 단편적이거나 균형이 잡히지 않은 관찰이나 시험에서 얻어진 약동학 자료들도 이용될 수 있다. 비선형 혼합-효과 모형 분석을 통해서 약동학과 약력학 파라미터의 분포를 결정하는 집단의 특성을 추정할 수 있다.

비선형 혼합-효과 모형 접근법에서는, 집단의 특성이 고정효과 파라미터(fixed-effects parameters)로부터 도출된 집단 평균값과 무작위효과 파라미터(random-effects parameters)에서 유래하는 분산-공분산 값과 관련된 집단내 변이로 이루어진다. 비선형 혼합-효과 모형 접근법에서는 개인별 농도 자료 전체로부터 집단의 파라미터들이 직접적으로 추정된다. 자료가 희박한(sparse) 경우에도 각 대상자별의 개별성은 유지된다. 집단 약동학에서의 비선형 혼합-효과 모형화 방법에 대한 자세한 내용은 다음에 기술하였다.

