# 집단 약동학 접근법을 사용하는 경우 {#indication}

일반적으로, 약물 개발 단계뿐만 아니라 개발 후에도 집단 약동학 접근법은 대상자의 특성과 투약, 약물 분포 등에 대한 정량적 이해를 높이기 위해 사용된다. 집단 약동학 접근법은 목표 집단에서 설명할 수 있는 변동이나 약물 행태(drug behavior)에 영향을 주는 요인을 찾고자 할 때 도움이 된다. 비선형 혼합-효과 모형을 이용한 접근은 흔히 용량적정(titration) 또는 효과 제어(effect controlled) 연구로 알려진 용량-범위 연구 (dose-ranging study)와 같은 조정 가능한 연구 설계(adaptive study design)에서 특히 유용하다.

집단 약동학 모형화는 개체간 약동학 변이로 인하여 목표 집단 중 일부 소집단에서 용량조절이 필요할 수 있다는 정보가 이미 합리적으로 수집된 경우에 더욱 의미가 크다. 집단 약동학 모형이 의미있는 경우는 (1)약물을 투여받게 되는 집단이 상당히 이질적(heterogeneous)인 경우와 (2)치료적 목표 농도 범위(target concentration window)가 상대적으로 좁은 경우이다.

약물 개발의 다음 단계에서 약물이 어떻게 사용될지에 대한 정보를 모으는 1상 임상과 후기 2b상 임상의 반응 표면 모형(response surface model)의 집단 파라미터를 추정하기 위해 집단 약동학 접근법을 사용할 수 있다. 집단 약동학 접근법은 더 유용한 정보를 주는 설계와 실험 분석을 제안함으로써 약물 개발 과정의 효율성(efficiency)과 특수성(specificity)을 증가시켜 준다. 광범위한 시료채취가 이루어지는 1상과 2상 임상연구에서는 복잡한 자료 분석법이 필요하지 않을 수도 있다.

2-단계 접근법을 이용한 자료 분석이 가능하고 공변량에 대한 파라미터의 의존성(dependence)을 모형화하기 위해 표준 회귀 분석을 사용할 수 있다. 그렇지 않으면, 개별 1상 및 2b상 임상연구의 자료를 모아(pooled) 비선형 혼합-효과 모형 접근법을 이용하여 분석할 수 있다.

또한, 집단 약동학 접근법은 초기 2a상과 3상 연구에서 약물 안전성(유효성)에 대한 정보와 고령자과 같은 특수 집단에서의 약동학적 추가 정보를 얻기 위해서도 사용될 수 있으며 시판 후 조사 연구(postmarketing surveillance study, phase 4)에서도 유용하다. 약물 개발에서 3상 및 4상 단계의 임상연구에서는 전체 집단 약동학 시료채취 설계(full population pharmacokinetics sampling design), 즉 다양한 시점에서 각 시험대상자로부터 1～6회의 시료를 채취하는 설계가 적합하다. 이러한 시료채취 설계(sampling design)는 신약 평가(new drug evaluation), 규제 결정(regulatory decision making), 허가사항 기재(drug labeling) 추가 등에 중요한 정보를 제공한다.

