# 자료 분석 {#analysis}

탐색 및 확증 시험 단계에서의 계획, 설계 및 분석 등 신약 개발의 여러 단계에서 집단
약동학의 모형화가 사용될 수 있다. 따라서 계획서에는 검증될 약동학 모형에 대해 기
술해야 한다. 자료 시각화, 모형 검증, 자료 목록과 같이 모형에 대한 세부적인 정보도
제공해야 한다.
집단 약동학 자료 분석은 다음과 같은 3단계의 절차로 수행된다.
(1) 탐색적 자료 분석, (2) 집단 약동학 모형 개발, (3) 모형의 타당성 검증(validation).
자료 분석 계획은 연구 계획서에 명확하게 정의되어야 한다.

## 탐색적 자료 분석
탐색적인 자료 분석은 그래프나 통계적인 기법을 사용하여 집단 분석 자료의 양상과
특징들을 분리하고 밝혀내는 작업이다. 이러한 탐색적인 자료 분석이 기존 모형이 아닌

예상하지 못했던 모형의 개발이나 적용의 계기가 될 수도 있다.
탐색 과정에서 유연성은 매우 중요하다. 연속적인 분석 과정에서 새롭게 밝혀진 자료의
패턴에 따른 대응을 하는 경우나, 자료의 구조를 분석하는 경우 모두에서 유연성은 중
요하다.
대부분의 집단 약동학 분석은 자료에 대해 명확한 가정을 바탕으로 수행하게 된다.
따라서 분석의 타당성은 가정들의 타당성에 의해 결정된다. 탐색적인 자료 분석 기법들은
자료의 가정을 확인하거나, 가정이 충족되지 않는 경우에 수정 방향을 제시하는 진단
도구가 된다.
집단 약동학 분석을 위한 탐색적인 자료 분석의 경우 더욱 섬세한 집단 모형 기법이
연계되어야 한다. 탐색적 자료 분석의 수행과 관련된 사항은 집단 약동학 분석 보고서에
잘 기술되어야 한다.

## 집단 약동학 모형 개발

### 목적, 가설, 가정

집단 약동학 분석을 시행할 때에는 그 목적을 명확히 하여야 한다. 알고자 하는 가설은
분명하게 기술되어야 하며, 개체간의 무작위효과와 잔차(residual errors)의 분포와 같이
분석에 내재된 가정들 또한 분명하게 기술되어야 한다.

### 모형 구축

추후 재현이 가능하도록 집단 모형을 구축하는 단계에 대한 윤곽을 보고서에 잘 기술
하여야 한다. 모형 구축 과정에서 교란, 공변량, 파라미터 등을 제거하는 기준과 근거
또한 분명하게 기술해야 한다. 최종 모형에 도달하기 위해 모형을 단순화하는 기준과 근거
역시 명확하게 설명해야 한다.

### 결과 신뢰성

분석결과의 신뢰성은 예측농도 대비 관측농도의 그래프(predicted versus observed
concentration), 예측농도와 실제 자료를 겹쳐 그린 그래프(predicted concentration
superimposed on the data), 파라미터의 사후 추정치 대비 공변량의 그래프(posterior
estimates of parameter versus covariate values) 등과 같은 그래프 진단을 통한 상세한
검토로 확인할 수 있다. 파라미터 추정치, 표준오차, 사례 삭제를 통한 진단(case

deletion diagnostics), 민감도 분석을 통한 확인도 적절할 수 있다.
파라미터의 신뢰구간(표준오차)은 비모수적 기법인 잭나이프(jackknife) 또는 프로파일
우도 그래프(profile likelihood plot) 등을 통해 얻어질 수 있다.
통계적 모형의 비선형성과 특정 문제가 수치 계산상의 어려움을 야기하고 추정 알고리
즘의 적절치 못한 목적 함수값의 최소화를 야기할 수 있다. 특정 측정값에 민감한 최
대우도산출 과정은 모형의 안정성 확인을 위해 사용할 수 있다.
집단 약동학 연구 결과의 질과 모형의 완건성(robustness)을 평가하는 것이 중요하다.
민감도 분석을 통한 모형의 완건성 평가가 그 방법일 수 있다. 완건성에 대한 근거를
제시하는 것은 곧 분석의 결과가 합리적이고 분석자에 의한 영향을 받지 않는다는 것을
보여준다.


## 모형 타당성 검증(Model Validation)

모형 타당성 검증(model validation) 목적은 타당성(validation) 검증 자료 세트에서 모
형이 잘 작동되며 잘 적용되는지 여부를 검토하는 것이다. 즉, 타당성 검증은 모형을
구축할 때 사용하지 않은 지표 자료를 사용하여 개발된 모형의 예측성을 평가하는 것으로
정의할 수 있다(예, 모형 파라미터 추정과 함께 모형 형태).
타당성 검증은 분석의 목적에 따라 결정된다. 어떤 모형은 특정 목적에는 적합하지만
다른 목적에서는 적합하지 않을 수 있다. 항상 맞거나 항상 틀린 모형은 없고, 항상 맞
거나 항상 틀린 적합(fitting)도 없다. 따라서 선정된 모형 타당성 검증 및 결과의 해석이
적합한지 여부에 분석자의 판단이 주요한 역할을 한다.
현재 집단 약동학 모형의 타당성 검증에 대하여 모두가 일반적으로 동의하는 적절한
통계적 방법은 없다. 미지의 공변량 효과와 비선형성으로 인해, 모형이 복잡하며 정확히
알 수 없기 때문에 타당성 검증 방법의 선택은 분석 목적에 따라 달라질 수 있다.
본 가이드라인에서는 타당성 검증의 예측적 기능에 중점을 두었다.
모든 집단 약동학 모형에서 타당성 검증이 필요한 것은 아니다. 만일 집단 약동학 분석의
결과가 의약품의 허가사항에 반영되어야 하는 경우라면, 모형 타당성 검증이 권장되며,
모형 타당성 검증 절차 또한 계획서에 통합적으로 함께 기술되어야 한다. 만약 집단
약동학 모형 구축의 목적이 약물의 변이 정도가 용량 조절을 권장할 정도는 아니라는 것을
설명하고 허가사항에 기술적인 정보를 추가하기 위한 것이라면, 모형에 대한 타당성 검증
없이 안정성 평가만 수행해도 된다.
타당성 검증 방법은 여전히 평가 중이며 추가적인 시험이 요구될 수 있으나, 일반적으로
아래의 두 가지 종류의 타당성 검증 방법이 사용되어 왔다.

### 타당성 검증 종류

첫 번째 종류의 타당성 검증은 외적 타당성 검증(external validation)으로 완성된 모형에
다른 연구의 새로운 자료 세트를 적용하여 모형을 평가하는 가장 엄격한 방법이다.
다른 방법은 내적 타당성 검증(internal validation)으로 자료를 조각내어 나누어서
(datasplitting) 다시 추출하는 기법을 사용하는 방법이다(교차 타당성 검증
(cross-validation), 붓스트랩(bootstrapping)).
자료 조각 기법은 모형 평가를 위해 새로운 자료를 수집하는 것이 현실적으로 어려울
경우에 타당성 검증 자료를 만들어내는 유용한 방법이다. 자료 조각 기법의 단점은 모
형의 예측 정확도가 일반적으로 자료를 조각내는데 사용된 표본의 크기에 따라 좌우된
다는 점이다.
자료 조각 기법의 예측 정확도를 최대화하기 위해서는, 모형을 구축하고 평가하는데
전체 샘플을 사용하는 것을 권장한다. 좀 더 예측성이 높은 개선된 모형을 얻기 위해서
지표 세트와 타당성 검증 자료 세트를 다시 섞어서 사용하는 경우에는, 자료 조각 기법
으로 만들어진 최종 모형이 검증되지 않을 수도 있다. 그러나, 자료 조각 기법을 사용
하는 경우에는 무작위로 추출된 2/3 가량의 자료(지표 세트)를 모형을 구축하는데 사
용하고, 남은 자료(타당성 검증 세트)를 이용하여 모형의 타당성을 검증하게 된다. 만일
지표 세트가 타당성 검증 과정까지 남게 되는 경우에는, 이를 타당성 검증 세트와 섞어서
사용하고, 최종 모형 결정을 위해 최종 모형이 그 혼합된 자료에 모형에 적합한지 확
인해 볼 수 있다.
또 다른 내적 타당성 검증 기법은 재추출(resampling)이다. 재추출 방법에는 교차 타당성
검증(cross-validation)과 붓스트랩(bootstrapping), 두 가지 방법이 있다. 교차 타당성 검
증은 자료 조각(data-splitting)을 반복하여 사용하는 방법이다. 이는 (1) 모형 구축을 위해
사용되는 자료 세트의 크기가 다른 방법에 비해 크고 이로 인해 추정과정에서 무시되는
자료가 작다는 장점이 있다. 또한, (2) 단일 샘플의 분할에 의존하지 않기 때문에 변이성이
감소하게 된다.
전체 타당성 검증 과정이 반복될 때에는 정확도에 있어 추정치의 큰 변이로 인하여, 교차
타당성 검증은 효율적인 방법은 아니다.
또 다른 재추출 방법인 붓스트랩은 교차 타당성 검증과 같이 모형 구축에 모든 자료를
사용한다는 장점이 있다. 소아 환자에서처럼 윤리적인 문제나 의학적인 사유로 표본
크기가 제한적일 수밖에 없는 경우, 집단 모형을 평가하는데 매우 유용할 수 있다.

### 타당성 검증 방법

문헌이나 허가 자료로 제출되는 모형 타당성 검증의 여러 방법들의 장점과 단점을 위에서
논의하였다.
완벽한 확률 모형의 타당성을 검증하는 기술은 여전히 발전하고 있기 때문에, 새로운
방법의 수용에 대해서도 적극적이어야 한다. 허가 자료로 제출되는 경우에는 모형의
타당성 검증 방법과 선정 근거를 상세하게 기술해야 한다.
여기에서는 집단 모형의 예측 기능을 평가하는데 사용하는 몇 가지 방법들을 간략히
기술하고자 한다.

#### 농도의 예측 오차 계산(Calculating Prediction Errors on Concentrations)

농도 자료의 예측 오차는 농도의 실측치와 모형을 통한 예측치 간의 차이를 계산하여
구한다. 계산한 평균 예측 오차는 정확도의 지표로서 사용되고, 평균 절대 오차(또는
평균 절대 제곱 오차의 제곱근)는 정밀도의 지표로서 사용된다.
이 방법은 한 대상자 당 1개의 자료가 있는 경우 가장 유용하게 사용된다. 그러나 한
대상자 당 1개 이상의 자료가 있는 경우, 각 자료의 예측 오차는 독립적이지 않고
이러한 기능 지표의 추정치는 신뢰도가 낮기 때문에 부적합하다. 그러나 이러한 접
근법은 동일한 개체에서 반복적인 비독립적인 실측치가 있는 경우도 고려할 수 있도록
하여, 그 한계를 극복할 수 있게 개선되었다.

#### 표준화된 예측 오차의 계산(Calculating Standardized Prediction Errors)

표준화된 예측오차를 계산하면, 개체내 실측치의 변이와 상관관계를 설명할 수 있다.
정규화된 오차의 평균과 분산을 계산하고, 그 평균값이 유의하게 0과 다르며 표준
편차가 1에 가까운지를 평가하기 위해 z-test 와 같은 검사를 시행한다. 표준화된 예측
오차의 표준편차에 대한 신뢰구간을 구할 수 있다. 파라미터 추정 시에는 불확실성에
대해 고려하지 않았기 때문에, 타당성 검증 자료 세트를 적용할 경우 이러한 방법이
과도하게 보수적일 수 있다.

#### 공변량에 대한 잔차의 도식화(Plotting Residuals Against Covariates)

공변량에 대해 잔차를 도식화하는 것은 농도의 예측 오차에 대한 방법이다. 이 방법
은 통계적인 계산 및 검정을 하지 않는다는 점에서 다른 방법들과 차이가 있다. 최
종 모형을 고정하고 공변량으로부터 예측한 값과 타당성 검증 자료 세트 간의 잔차
를 표현한 간단한 그래프는 공변량 또는 소집단의 측면에서 모형의 임상적 유의성에
대한 정보를 제공한다.

#### 파라미터를 통한 타당성 검증(Validating Through Parameters)

파라미터를 통한 타당성 검증 방법은 모형의 파라미터 타당성 검증을 수행하여 농도의
예측오차에 발생할 수 있는 문제들을 방지할 수 있는 방법이다. 공변량이 있는 경우와
없는 경우에 타당성 검증 자료 세트로부터 모형의 파라미터가 예측되며, 이러한 예측에
대한 편향(bias)과 정밀도가 계산된다.

#### 사후 예측 확인

새로운 방법인 사후 예측 확인(posterior predictive check)이 현재와 미래 자료 세트의
중요한 임상적 특성이 모형에 의해 충실히 재현이 되는가를 결정하는데 유용할 수
있다. 그러나 이러한 접근법은 아직 널리 통용되고 있지는 않다.
앞서 언급한 바와 같이, 이 방법들은 집단 모형의 예측 기능을 평가하는데 유용하다.
이용할 검사용 자료 세트가 없는 경우에는 붓스트랩 접근법을 사용하는 것이 적절하다.
붓스트랩 시에는, 적당한 횟수(적어도 200회 이상)로 반복하여 얻어지는 붓스트랩 복제
값에 최종 모형을 반복적으로 적합(fitting)시켜서 얻어진 파라미터의 평균값들을 붓스
트랩 없이 얻어진 최종 집단 모형 파라미터 추정치와 비교하는 것이다. 그 대안으로서,
교차 타당성 검증을 할 수도 있다. 또한 사후 예측 확인 방법은 현재와 미래의 자료세
트의 중요한 특성이 정확하게 모형을 재현하는가를 확인하는데 유용한 것으로 밝혀져
있다.
모형 구축과 결과의 타당성 검증은 사용된 자료의 질에 의해 결정된다. 모형 타당성
검증과 연구 디자인은 매우 밀접한 관계가 있다. 선형 약동학 모형은 주어진 용량 범
위에서만 확인 가능하다. 따라서 모형의 가장 중요한 측면을 결정하기 위해서는 어느
정도의 예상과 심사숙고가 필요하다. 집단 약동학 모형 타당성 검증의 적절한 통계적
방법에 대해 일반적으로 합의된 방법은 없으므로, 타당성 검증의 쟁점에 다음의 질문을
던져 보는 것이 최선일 수 있다. “모형의 부족한 점이 모형으로부터 얻게 되는 실질적인
추론에 인지할만한 영향을 미치는가?”
타당성 검증이 수행된 후보 모형 중에서 예측력이 가장 좋으면서, 가장 단순한 모형이
최종 모형이 된다.
타당성 검토를 위해서는 시각적 예측 확인(visual predictive check), 붓스트랩
(bootstrapping), numerical/posterior predictive check, delete-1 method/jack-knife 등을
사용하는 것을 권장한다.



