# 집단 약동학 결과보고서 {#report}

집단 약동학 연구가 임상연구의 부가연구로 수행된 경우, 모든 연구 결과는 통합되어야 한다. 집단 분석을 위해 여러 개의 집단 약동학 연구가 모아진 경우, 한 개의 집단 약동학 분석 보고서가 작성되어야 한다. 보고서에는 다음과 같은 내용들이 포함되어야 한다.

```
1. 요약
2. 서론
3. 목적 및 가설과 가정
4. 연구자료 및 방법
5. 결과
6. 논의
7. 결과의 적용
8. 부록
```

## 요약

집단 약동학 연구 전반에 대한 요약을 기술하며, 여기에는 연구의 맥락과 발견한 사항 및 결론에 대해 충분한 정보를 담고 있어야 한다.

## 서론

서론에서는 연구의 일반적인 의도를 간략하게 언급하여야 한다. 특히 임상 개발 단계에서 수행된 경우, 집단 약동학 연구를 수행하게 된 충분한 배경을 설명하고 연구의 특징을 기술하여야 한다.

## 목적 및 가설과 가정

연구와 분석의 목적은 보고서의 서론 부분 다음에 명확하게 기술하여야 한다. 일차적인 목적뿐 아니라, 이차적인 목적이 있는 경우 이를 기술하여야 한다. 만일 계획서가 승인된 이후 연구 목적을 수정하고자 하는 경우에는, 변경 사항을 집단 약동학 보고서에 명시하여야 한다. 보고서에는 검정하고자 하는 가설과 사용된 가정은 무엇인가에 대해 명확하게 기술하여야 한다.

## 연구자료 및 방법  

재료와 방법 부분은 반드시 계획서에 포함하여야 한다. 분석을 위해 여러 연구들의 자료를 합치게 되는 경우, 각 연구의 계획서를 기술하여야 한다. 연구 디자인, 계획한 표본 크기, 선정기준을 포함한 대상자 선정에 대한 정보 및 연구 기관에 대한 정보가 기재되어야 한다. 약물의 이름, 용량, 투여시각, 복약 순응도를 비롯한 약물 치료에 대한 정보도 기술되어야 한다. 또한 농도 분석법 및 자료 수집과 분석 방법에 대해서도 자세하게 기술되어야 한다.

1. 분석법: 이 부분에서는 약물의 농도를 측정하는 방법이 기술되어야 한다. 품질관리시료를 비롯한 농도 분석의 성능, 시료의 크로마토그램, 정량 곡선 등의 내용을 포함하고 있어야 하며, 농도 분석법의 타당성에 대해서 기술하여야 한다.
2. 자료: 보고서는 반응 변수와 모든 공변량에 대한 정보를 포함하여야 하며, 이러한 정보를 얻은 방법에 대하여 기술하여야 한다. 보고서에는 시료(예, 혈장)를 수집할 때의 시료채취 방법(예, 채혈방법)에 대한 내용과 공변량의 정확도, 정밀도 및 분포에 대한 정보를 포함하여야 한다. 자료 세트의 전자 복사본이 제출되어야 한다. 자료의 질 관리와 편집 절차에 대해서도 언급하여야 한다. 
3. 분석방법: 이 부분에서는 탐색적 자료분석을 포함하여 모형 구축 및 단순화의 기준과 과정에 대해 자세하게 기술하여야 한다. (1)선택된 집단 분석 방법, (2)파라미터화 과정 및 무작위효과의 분포 등 모형 구성요소에 대한 가정, (3)이러한 가정의 근거, (4)선택된 모형-적합 방법과 같은 연구에서 사용된 자료 분석 방법의 구성요소들은 모두 기술하여야 한다. 추가적으로, 이 부분에서는 유형의 구축과 단순화 단계에서의 대표적인 제어/명령 파일과 분석의 전반적인 흐름도(flow diagram) 뿐 아니라 이상치와 누락된 자료의 처리 방법을 기술하여야 한다.

## 결과

주요 분석 결과를 이해하기 쉬운 표와 그래프의 형태로 편집하여야 한다. 모형의 구축에 사용된 진단용 그래프와 검사의 신뢰도가 포함되어야 하고 해석과 적용을 돕기 위해, 결과에 대하여 철저하게 기술되어야 하며 최종 집단 모형 및 주요 중간 단계에서 얻어진 중요한 결과물이 포함되어야 한다.

## 논의

모형 구축과 단순화 과정의 근거, 결과의 해석, 계획서 위반, 그래프에 대한 설명과 논의
사항을 보고서에 이해하기 쉬운 문장으로 기술하여야 한다. 예로서, 체중에 따른 용량
조절, 크레아티닌 청소율과 약물의 청소율 간의 관계, 특수 환자 집단에 미치는 영향
등을 비롯하여 모형 개발로 예상할 수 있는 효과에 대해 언급하여야 한다.

## 결과의 적용

허가 사항에 정보 추가, 특수집단에서의 약물 용량 조절이나 안전성 정보 추가, 추가적인 연구 등과 같이 분석 결과의 사용에 대한 논의를 기술하여야 한다. 또한 통계적 유의성과 임상적 유의성 간의 관계에 대해 논의되어야 한다. 집단 약동학 분석 결과 특정 약동학 또는 약력학 파라미터에 통계적으로 유의한 차이가 관찰된다고 하더라도 이것은 임상적으로 어떠한 의미가 있는지는 검토되어야 한다. 임상약리학자 등의 전문가와 추가적으로 검토할 필요가 있다. 

추가적으로, 용량 조절에 대해 집단 약동학 모형을 적용하여 잠재적으로 가능한 반응에 대해 시뮬레이션한 결과를 그래프로 도식화하는 것을 권장한다. 

많은 경우 의사결정이 유의확률(p-value)과 같은 확률(probability)에 기반하여 이루어지나, 정확한 확률을 구할 수 없는 경우도 있으며, 우도(likelihood) 또는 우도비(likelihood ratio)에 기반한 의사 결정이 필요하거나 더 유용한 경우들이 흔히 있다. 또한 유의확률이나 가설 검정(hypothesis test)보다는 파라미터 추정(parameter estimation)이 더 유용한 경우가 많다.

집단 약동학 분석 결과를 검토할 때는 각 약동학/약력학 파라미터의 점 추정치가 통계적으로 유의한 차이가 있는지 여부보다는 그 차이의 크기(차이 또는 비에 대한 점 추정치)가 어느 정도인지, 각 집단의 변이의 크기(분산의 정도)가 어느 정도인지, 어느 한 집단의 변이 정도가 다른 집단의 변이에 포함되는지, 좀 더 효과나 독성에 가까운 지표 (AUC, C~max~ 등)들을 시뮬레이션했을 때 그 분포구간이 유사한지 등을 함께 검토하여야 한다.

시뮬레이션을 할 때에는 공변량 간이나 약동학/약력학 파라미터들 간에 독립을 가정할 수 없으므로 상관관계나 공분산을 고려하여야 한다. 또한 임상시험 간의 변이, 매 투약 간의 변이, 추정값의 불확실성도 가능하면 고려하는 것이 좋다.

약물에 대하여 알려져 있는 정보에 따라 요구되는 자료의 수준은 달라질 수 있다.

## 부록

부록은 집단 분석에 사용된 자료 세트에서 대표적인 부분을 포함하여야 한다. 중요하다고 간주되는 추가적인 그래프뿐만 아니라, 최종 모형 결과의 인쇄물과 함께 프로그래밍 코드가 포함되어야 한다. 분석이 추가적인 임상시험의 결과로서 수행되거나 독립적인 집단 약동학 연구로 수행되었는지에 상관없이 부록에는 연구 계획서가 포함되어야 한다.

